name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: 'Deploy app to production'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Installing Dependencies'
        uses: ./.github/actions/install

      - name: 'Pull Vercel Environment Information'
        run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app

      - name: 'Build Project Artifacts'
        run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app

      - name: 'Deploy Project Artifacts to Vercel'
        run: pnpm vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app

