name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Test & lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install
        working-directory: ./app

      - name: 'Running Unit Tests'
        run: pnpm test
        working-directory: ./app

      - name: 'Building'
        run: pnpm lint
        working-directory: ./app
