name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-preview:
    name: 'Deploy app to preview'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Installing Dependencies'
        uses: ./.github/actions/install

      - name: 'Pull Vercel Environment Information'
        run: pnpm vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app

      - name: 'Build Project Artifacts'
        run: pnpm vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app

      - name: 'Deploy Project Artifacts to Vercel'
        run: pnpm vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./app
